### ISSUE TITLE
Visualisation for the match-interaction question type

### ISSUE THREAD

**Issue by SillatL** [centre-for-educational-technology/tinda#9]
Most "õpetajakoolituse instrument" are based on the match-interaction question type. We need to find a way to visualize the data. Similarly to the digital competence questionnaire.

**Comment by pankajchejara23** [comment]
First prototype has been created. Yet to be pushed to server.
![image](https://user-images.githubusercontent.com/21138354/101989819-9b72d380-3cab-11eb-8d18-b9c019000051.png)

**Comment by pankajchejara23** [comment]
Changes are pushed to the server.
